In [1]:
# Bibliotheken abrufen
import json
import pandas as pd
import requests
import numpy as np

In [2]:
# URL als Variable definieren
url = "https://rodare.hzdr.de/api/records/?page=1&sort=mostrecent&size=1000"

In [3]:
# Funktion um Inhalt aus URL in r zu speichern
r = requests.get(url)

In [4]:
# JSON lesen lassen
json = r.json()

In [5]:
# ARRAY aufbauen um ???
data = np.zeros([json['hits']['total'],1])

In [6]:
# Definition einer Gesamtliste
list_all = []

In [7]:
# Definition einer Teilliste und for-Schleife, um den type der Records aus allen Einträgen auszulesen und aufzulisten
type_list = []
for index,record in enumerate(json['hits']['hits']):
    type_list.append(record['metadata']['resource_type']['type'])

In [8]:
# Hinzufügen der Teilliste zu Gesamtliste
list_all.append(type_list)

In [9]:
# Leerung der Teilliste und Füllung mit dem Publikationsdatum
type_list = []
for index,record in enumerate(json['hits']['hits']):
    type_list.append(record['metadata']['publication_date'])

In [10]:
# Hinzufügen der Teilliste zu Gesamtliste
list_all.append(type_list)

In [11]:
# Leerung der Teilliste und Füllung mit dem Zugriffsrecht für Records
# type_list = []
# for index,record in enumerate(json['hits']['hits']):
 #   type_list.append(record['metadata']['access_right'])

In [12]:
# Hinzufügen der Teilliste zu Gesamtliste
# list_all.append(type_list)

In [13]:
# Anzeigen der Gesamtliste 
list_all

[['dataset',
  'software',
  'software',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'software',
  'dataset',
  'dataset',
  'software',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'software',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'image',
  'software',
  'dataset',
  'dataset',
  'video',
  'software',
  'software',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'other',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'software',
  'video',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'software',
  'other',
  'dataset',
  'software',
  'dataset',
  'dataset',
  'dataset',
  'other',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'image',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'image',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'software',
  'other',
  'software',
  'software',
  'software',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'image',
  'image',
  'dataset',
  'dataset',
  'image',
  'image',
  'image',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'video',
  'dataset',
  'other',
  'other',
  'dataset',
  'other',
  'other',
  'other',
  'dataset',
  'dataset',
  'dataset',
  'image',
  'software',
  'dataset',
  'dataset',
  'dataset',
  'other',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'other',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'software',
  'dataset',
  'dataset',
  'image',
  'video',
  'image',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'other',
  'dataset',
  'image',
  'video',
  'dataset',
  'software',
  'dataset',
  'dataset',
  'dataset',
  'software',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'image',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'video',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'software',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'software',
  'dataset',
  'software',
  'dataset',
  'presentation',
  'presentation',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'software',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'presentation',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'software',
  'dataset',
  'dataset',
  'dataset',
  'presentation',
  'dataset',
  'dataset',
  'other',
  'presentation',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'dataset',
  'image'],
 ['2021-07-03',
  '2021-07-01',
  '2021-07-01',
  '2021-06-22',
  '2021-06-23',
  '2021-06-08',
  '2020-12-09',
  '2021-05-13',
  '2021-05-31',
  '2021-05-27',
  '2021-05-25',
  '2021-04-23',
  '2021-05-21',
  '2021-05-21',
  '2021-01-28',
  '2021-05-03',
  '2021-05-03',
  '2021-05-03',
  '2021-04-30',
  '2021-04-29',
  '2021-04-30',
  '2021-04-19',
  '2021-04-29',
  '2021-04-01',
  '2021-04-19',
  '2021-01-12',
  '2021-04-21',
  '2021-04-08',
  '2021-04-16',
  '2021-04-13',
  '2021-04-15',
  '2021-04-13',
  '2020-10-06',
  '2021-04-07',
  '2021-01-20',
  '2021-04-01',
  '2021-04-01',
  '2021-03-31',
  '2021-03-29',
  '2021-03-23',
  '2021-03-11',
  '2021-01-28',
  '2021-03-17',
  '2021-03-15',
  '2021-03-15',
  '2021-03-15',
  '2021-03-10',
  '2021-03-10',
  '2021-03-10',
  '2021-03-10',
  '2021-03-10',
  '2021-03-10',
  '2021-03-10',
  '2021-03-10',
  '2021-03-10',
  '2021-03-10',
  '2021-03-10',
  '2021-03-10',
  '2021-03-10',
  '2021-03-10',
  '2021-03-10',
  '2021-03-08',
  '2021-03-10',
  '2021-03-10',
  '2021-03-09',
  '2021-03-04',
  '2021-03-02',
  '2021-01-06',
  '2021-03-01',
  '2021-02-24',
  '2021-02-25',
  '2021-02-23',
  '2021-02-18',
  '2021-02-11',
  '2021-02-08',
  '2021-02-08',
  '2021-02-09',
  '2021-01-28',
  '2021-02-08',
  '2021-01-28',
  '2021-01-28',
  '2021-01-29',
  '2020-09-16',
  '2021-01-08',
  '2021-01-31',
  '2021-01-29',
  '2021-01-06',
  '2021-01-23',
  '2021-01-22',
  '2021-01-31',
  '2021-01-22',
  '2020-09-08',
  '2020-04-06',
  '2021-01-12',
  '2021-01-07',
  '2021-01-07',
  '2021-05-01',
  '2021-01-06',
  '2021-01-05',
  '2021-01-04',
  '2020-12-19',
  '2020-12-01',
  '2020-12-17',
  '2020-12-17',
  '2020-12-16',
  '2020-12-16',
  '2020-07-05',
  '2020-12-11',
  '2020-12-15',
  '2020-06-22',
  '2020-09-16',
  '2020-09-14',
  '2020-06-08',
  '2020-11-06',
  '2020-02-26',
  '2020-12-14',
  '2020-12-14',
  '2020-09-25',
  '2020-12-11',
  '2020-07-22',
  '2020-11-26',
  '2020-11-26',
  '2020-11-30',
  '2020-11-27',
  '2020-11-27',
  '2020-11-26',
  '2020-11-26',
  '2020-11-26',
  '2020-11-24',
  '2020-12-15',
  '2020-11-15',
  '2020-11-11',
  '2020-11-10',
  '2020-11-09',
  '2020-10-28',
  '2020-09-09',
  '2020-10-21',
  '2020-10-21',
  '2020-10-19',
  '2020-09-17',
  '2020-03-23',
  '2020-10-13',
  '2020-09-28',
  '2020-10-08',
  '2020-10-06',
  '2020-10-05',
  '2020-10-01',
  '2020-09-25',
  '2020-09-22',
  '2020-09-22',
  '2020-04-02',
  '2020-09-08',
  '2020-09-08',
  '2020-09-08',
  '2020-09-08',
  '2020-09-03',
  '2020-09-03',
  '2020-08-27',
  '2020-08-06',
  '2020-04-14',
  '2020-08-03',
  '2020-01-09',
  '2020-07-21',
  '2020-07-16',
  '2020-07-14',
  '2020-07-08',
  '2019-12-09',
  '2020-07-02',
  '2020-07-01',
  '2020-06-29',
  '2020-06-25',
  '2020-06-18',
  '2020-06-16',
  '2020-06-11',
  '2020-06-09',
  '2020-06-03',
  '2020-06-05',
  '2020-06-03',
  '2020-06-03',
  '2020-05-25',
  '2020-05-25',
  '2020-05-20',
  '2020-01-29',
  '2020-05-12',
  '2020-05-19',
  '2020-04-20',
  '2020-05-18',
  '2020-05-10',
  '2020-05-11',
  '2020-05-08',
  '2020-04-16',
  '2020-04-17',
  '2020-04-15',
  '2020-01-17',
  '2020-04-02',
  '2020-03-18',
  '2020-02-27',
  '2020-02-18',
  '2020-02-12',
  '2020-02-04',
  '2020-02-03',
  '2020-02-03',
  '2020-01-16',
  '2020-01-24',
  '2020-01-17',
  '2019-07-01',
  '2019-07-01',
  '2019-11-23',
  '2020-01-07',
  '2020-01-10',
  '2020-01-07',
  '2020-01-07',
  '2020-01-10',
  '2020-01-10',
  '2019-03-14',
  '2020-01-06',
  '2019-11-18',
  '2019-11-27',
  '2019-11-26',
  '2019-12-01',
  '2019-12-01',
  '2019-08-01',
  '2019-08-01',
  '2019-10-30',
  '2019-09-11',
  '2019-09-04',
  '2019-09-02',
  '2019-08-19',
  '2019-08-16',
  '2019-08-16',
  '2019-06-26',
  '2019-06-18',
  '2019-06-13',
  '2019-05-20',
  '2019-03-06',
  '2019-03-06',
  '2019-03-04',
  '2019-02-22',
  '2019-01-16',
  '2018-12-31',
  '2018-12-04',
  '2018-09-18',
  '2018-11-18',
  '2018-10-30',
  '2018-10-23',
  '2018-10-18',
  '2018-09-19',
  '2018-09-18',
  '2018-09-05',
  '2018-08-17',
  '2018-05-22',
  '2018-05-09',
  '2018-04-25',
  '2018-04-12',
  '2018-03-20',
  '2018-02-28']]

In [14]:
# was macht das?
Meta_dict = {}
# was macht das?
Meta_dict['publication_date'] = type_list

In [15]:
# was macht das? 
Meta_dict['type'] = list_all[0]

In [16]:
# Umwandlung der Liste in ein DataFrame 
# Hier muss jetzt ein Problem auftreten - denn es werden unten nun unter publication_date dieaccessrechte angegeben
# was ist der Fehler? Deswegen mit # rausgenommen (Verstehe hier die Idee der Konstruktion nicht zur Gänze)
df = pd.DataFrame(Meta_dict)

In [17]:
# Anzeige des Dataframe
df

    publication_date      type
0         2021-07-03   dataset
1         2021-07-01  software
2         2021-07-01  software
3         2021-06-22   dataset
4         2021-06-23   dataset
..               ...       ...
251       2018-05-09   dataset
252       2018-04-25   dataset
253       2018-04-12   dataset
254       2018-03-20   dataset
255       2018-02-28     image

[256 rows x 2 columns]